Technology-Fundamentals-with-CSharp-January-2019/28-BasicCRUDExercise/TeisterMask/Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TeisterMask.Models
{
    public class Task
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Status { get; set; }
    }
}

Technology-Fundamentals-with-CSharp-January-2019/28-BasicCRUDExercise/TeisterMask/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TeisterMask.Data;

namespace TeisterMask.Controllers
{
    public class TaskController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            using (var db = new TeisterMaskDbContext())
            {
                var allTasks = db.Tasks.ToList();
                return View(allTasks);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Create(string title, string status)
        {
            if (string.IsNullOrEmpty(title) || string.IsNullOrEmpty(status))
            {
                return RedirectToAction("Index");
            }
            Models.Task task = new Models.Task
            {
                Title = title,
                Status = status
            };
            using (var db = new TeisterMaskDbContext())
            {
                db.Tasks.Add(task);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            using (var db = new TeisterMaskDbContext())
            {
                var taskToEdit = db.Tasks.FirstOrDefault(t => t.Id == id);
                if (taskToEdit == null)
                {
                    return RedirectToAction("Index");
                }
                return this.View(taskToEdit);
            }
        }

        [HttpPost]
        public IActionResult Edit(Models.Task task)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            using (var db = new TeisterMaskDbContext())
            {
                var taskToEdit = db.Tasks.FirstOrDefault(t => t.Id == task.Id);
                taskToEdit.Title = task.Title;
                taskToEdit.Status = task.Status;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            using (var db = new TeisterMaskDbContext())
            {
                Models.Task taskDetails = db.Tasks.FirstOrDefault(t => t.Id == id);
                if (taskDetails == null)
                {
                    RedirectToAction("Index");
                }
                return View(taskDetails);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            using (var db = new TeisterMaskDbContext())
            {
                Models.Task taskDetails = db.Tasks.FirstOrDefault(t => t.Id == id);
                if (taskDetails == null)
                {
                    RedirectToAction("Index");
                }
                return View(taskDetails);
            }
        }

        [HttpPost]
        public IActionResult Delete(Models.Task task)  
        {
            using (var db = new TeisterMaskDbContext())
            {
                var taskToDelete = db.Tasks.FirstOrDefault(t => t.Id == task.Id);
                if (taskToDelete == null)
                {
                    RedirectToAction("Index");
                }
                db.Tasks.Remove(taskToDelete);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Technology-Fundamentals-with-CSharp-January-2019/28-BasicCRUDExercise/TeisterMask/Views/Task/Create.cshtml
@model TeisterMask.Models.Task

@{
    ViewBag.Title = "Create";
}

<header>
	<h3>Create New Task</h3>
</header>

@using (Html.BeginForm("Create", "Task", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div>
		<label class="desc" for="title">Title</label>
		<div>
			<input id="title" name="title" type="text" class="field text fn" value="" size="8" tabindex="1" autofocus>
		</div>
	</div>

	<div>
		<fieldset>
			<legend id="title5" class="desc">
				Status
			</legend>

			<div>
				<div>
					<input id="status1" name="status" type="radio" value="Open" tabindex="2" checked>
					<label class="choice" for="status1">Open</label>
				</div>
				<div>
					<input id="status2" name="status" type="radio" value="In Progress" tabindex="3">
					<label class="choice" for="status2">In Progress</label>
				</div>
				<div>
					<input id="status3" name="status" type="radio" value="Finished" tabindex="4">
					<label class="choice" for="status3">Finished</label>
				</div>
			</div>
		</fieldset>
	</div>

	<div>
		<div>
			<input class="button" type="submit" value="Create">
			<a class="button cancel" href="/">Cancel</a>
		</div>
	</div>
}

Technology-Fundamentals-with-CSharp-January-2019/28-BasicCRUDExercise/TeisterMask/Views/Task/Delete.cshtml
@model TeisterMask.Models.Task

@{
	ViewBag.Title = "Delete Task";
}

<header>
	<h3>Delete Task</h3>
</header>

@using (Html.BeginForm("Delete", "Task", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div>
		<label class="desc" for="title">Title</label>
		<div>
			<input id="title" name="title" type="text" class="field text fn" value="@Model.Title" size="8" tabindex="1" autofocus disabled="disabled">
		</div>
	</div>

	<div>
		<fieldset>
			<legend id="title5" class="desc">
				Status
			</legend>

			<div>
				<div>
					<input id="status1" disabled="disabled" name="status" type="radio" value="Open" tabindex="2" @(Model.Status == "Open" ? "checked" : "")>
					<label class="choice" for="status1">Open</label>
				</div>
				<div>
					<input id="status2" disabled="disabled" name="status" type="radio" value="In Progress" tabindex="3" @(Model.Status == "In Progress" ? "checked" : "")>
					<label class="choice" for="status2">In Progress</label>
				</div>
				<div>
					<input id="status3" disabled="disabled" name="status" type="radio" value="Finished" tabindex="4" @(Model.Status == "Finished" ? "checked" : "")>
					<label class="choice" for="status3">Finished</label>
				</div>
			</div>
		</fieldset>
	</div>

	<div>   
		<div>
            <input class="button" type="submit" value="Delete">
			<a class="button cancel" href="/">Cancel</a>
		</div>
	</div>
}

Technology-Fundamentals-with-CSharp-January-2019/28-BasicCRUDExercise/TeisterMask/Views/Task/Edit.cshtml
@model TeisterMask.Models.Task

@{
	ViewBag.Title = "Edit Task";
}

<header>
	<h3>Edit Task</h3>
</header>

@using (Html.BeginForm("Edit", "Task", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div>
		<label class="desc" for="title">Title</label>
		<div>
			<input id="title" name="title" type="text" class="field text fn" value="@Model.Title" size="8" tabindex="1" autofocus>
		</div>
	</div>

	<div>
		<fieldset>
			<legend id="title5" class="desc">
				Status
			</legend>

			<div>
				<div>
					<input id="status1" name="status" type="radio" value="Open" tabindex="2" @(Model.Status == "Open" ? "checked" : "")>
					<label class="choice" for="status1">Open</label>
				</div>
				<div>
					<input id="status2" name="status" type="radio" value="In Progress" tabindex="3" @(Model.Status == "In Progress" ? "checked" : "")>
					<label class="choice" for="status2">In Progress</label>
				</div>
				<div>
					<input id="status3" name="status" type="radio" value="Finished" tabindex="4" @(Model.Status == "Finished" ? "checked" : "")>
					<label class="choice" for="status3">Finished</label>
				</div>
			</div>
		</fieldset>
	</div>

	<div>
        <div>
            <input class="button" type="submit" value="Edit">
            <a class="button cancel" href="/">Cancel</a>
        </div>
	</div>
}

Technology-Fundamentals-with-CSharp-January-2019/28-BasicCRUDExercise/TeisterMask/Views/Task/Index.cshtml
@model List<TeisterMask.Models.Task>

@{
	ViewBag.Title = "Index";
}

<div class="container">
	@Html.ActionLink("Create New Task", "Create", "Task", null, new { @class = "button" })
</div>

<div class="tasks container">
	<header>
		<div class="column header open">Open</div>
		<div class="column header inProgress">In Progress</div>
		<div class="column header finished">Finished</div>
	</header>
	<ul class="column open">
		@foreach (var task in Model.Where(t => t.Status == "Open").ToList())
		{
        <li>
            @task.Title
            @Html.ActionLink(" ", "Edit", "Task", new { id = task.Id }, new { @class = "icon edit" })
            @Html.ActionLink(" ", "Delete", "Task", new { id = task.Id }, new { @class = "icon delete" })
        </li>
		}
	</ul>
	<ul class="column inProgress">
		@foreach (var task in Model.Where(t => t.Status == "In Progress").ToList())
		{
        <li>
            @task.Title
            @Html.ActionLink(" ", "Edit", "Task", new { id = task.Id }, new { @class = "icon edit" })
            @Html.ActionLink(" ", "Delete", "Task", new { id = task.Id }, new { @class = "icon delete" })
        </li>
		}
	</ul>
	<ul class="column finished">
		@foreach (var task in Model.Where(t => t.Status == "Finished").ToList())
		{
        <li>
            @task.Title
            @Html.ActionLink(" ", "Edit", "Task", new { id = task.Id }, new { @class = "icon edit" })
            @Html.ActionLink(" ", "Delete", "Task", new { id = task.Id }, new { @class = "icon delete" })
        </li>
		}
	</ul>
</div>